version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ecommerce
      MB_DB_PORT: 5432
      MB_DB_USER: pguser
      MB_DB_PASS: pgpassword
      MB_DB_HOST: postgres  # Use the service name here
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
